name: Generate Reports

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate flaky test reports
        run: node generateReports.js

      - name: Upload summary HTML
        uses: actions/upload-artifact@v3
        with:
          name: flaky-summary-html
          path: reports/flaky-summary.html

      - name: Upload PDF report (optional)
        uses: actions/upload-artifact@v3
        with:
          name: flaky-summary-pdf
          path: reports/flaky-summary.pdf
